language: java
deploy:
  provider: heroku
  app: protected-headland-05984
  api_key:
    secure: DaQeyW7coIo2CFiSuOklZBBCxm4yp4urI63WmCPWIkZIWozj64zH6kM5JNh994EBLefDrKwwv7zwFbZmPl9X+k4MQYPXmT7ykvp42lvV51pFo1JEZ/vTsyo4nt/5WCLxmZYGpGhwTB3j/Av3S1hPLkiE+d6iP/fkBS9If3LiObT51jv6qANK7gN5Kmtwq0Bw8GmpdbZoA0HEoYP/aIynL82eF4VcJ9fjTBRkgPCMf27osAhjBzEptN3YNnZt6PN3BPmrT8YoevCfds4drORpWCgcGr3Y4c2xi/HtL2+PMKjMMlVaEpUA7O6Na7DktN/4Yai5aWxem9q5YXgImqK3MY423Lg0ahf8Xo2Y3880QKsUi2HoH8XqdcXjmcL/DeXHINUzTSLnTxgbEVsiJFx3+Dqg8esQVcewxywlk3Ec38RbxHqM6CualPJIXFwODBEa/Iv9FLQz7bhfQpcJN4GBp3YjgFavh3cS4CbIWbgb0z13n7YdUObkTcwxPP2HNiNrVoo1drz0DKmMk+LK9bdNS/HTH8VXe8UK1QqmCg2vr7TYzJR+U5zUPgXkY6wbh+6IQHnL+F2jBKD0QXmhim1V92d/z7UJEvnpH2bTsaXlSUTNHw1shmQAJo6wL4dznOE/R//tG3oeyCnDx4DVO8TedPkB9nQa712d5Kv6RFWr8OU=
